### ISSUE TITLE
App Crash when calling showSurvey in SDK 1.9.0

### ISSUE THREAD

**Issue by ponsuyambu** [qualaroo/AndroidSDK#12]
App is getting crashed with the below exception when I tried to show the survey. I am sure that I have properly initialized the SDK and surveys. Please help asap

**Qualaroo Debug Log:**
2019-08-23 11:57:03.526 I/QularooSDK: Initialized QualarooSdk
2019-08-23 11:57:05.533 D/QularooSDK: Acquired 4 surveys
2019-08-23 11:57:05.538 D/QularooSDK: No failed reports found
2019-08-23 11:57:05.960 D/QularooSDK: Trying to show survey: test_survey
2019-08-23 11:57:05.996 D/QularooSDK: Displaying survey test_survey

**Test Device:** OnePlus 6, Android 9

**Logcat crash log**
`Process: com.goeuro.rosie.debug, PID: 30493
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.goeuro.rosie.debug/com.qualaroo.QualarooActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.qualaroo.internal.model.Message.a()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.qualaroo.internal.model.Message.a()' on a null object reference
        at com.qualaroo.internal.d.a.a(Unknown Source:10)
        at com.qualaroo.internal.d.a.b(Unknown Source:96)
        at com.qualaroo.internal.d.a.a(Unknown Source:104)
        at com.qualaroo.internal.d.a.b(Unknown Source:83)
        at com.qualaroo.internal.d.a.a(Unknown Source:74)
        at com.qualaroo.internal.d.a.b(Unknown Source:41)
        at com.qualaroo.internal.d.a.<init>(Unknown Source:52)
        at com.qualaroo.ui.h.<init>(Unknown Source:87)
        at com.qualaroo.ui.e.<init>(Unknown Source:36)
        at com.qualaroo.ui.e.<init>(Unknown Source:0)
        at com.qualaroo.ui.e$a.a(Unknown Source:90)
        at com.qualaroo.Qualaroo.a(Unknown Source:4)
        at com.qualaroo.QualarooActivity.onCreate(Unknown Source:47)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)`

**Comment by scana** [comment]
Hi @ponsuyambu!
Sorry for your trouble.
Could you please PM me your account name and survey's alias that you are trying to show to marcin@qualaroo.com?

**Comment by ponsuyambu** [comment]
Hi @scana sent a mail to you

**Comment by ryanmcgough** [comment]
Hi @scana. I am receiving the same error as @ponsuyambu when trying to show a survey. if it's best to email you the information mentioned above, please let me know!

**Comment by ponsuyambu** [comment]
@scana Do you have any update?

**Comment by natanio** [comment]
@ponsuyambu Qualaroo has fixed the issue for your surveys, and will be deploying a permanent fix for the issue soon. If you try again now though, your app should not crash.

**Comment by natanio** [comment]
@ryan-braindo Please email support@qualaroo.com with the details, and mention this issue.

**Comment by ryanmcgough** [comment]
Hey @natanio, when clicking on the survey that was crashing last week to get the logs, it appears to be working now. Thank you for following up!

**Comment by ponsuyambu** [comment]
It is working now, thanks!
