### ISSUE TITLE
App crashing because JobIntentService

### ISSUE THREAD

**Issue by Hannibalem** [qualaroo/AndroidSDK#14]
Hi, recently we added your SDK to our project and we have started to get tons of crashes in Android >= 8 devices because of the following: 

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:354)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
Caused by java.lang.SecurityException: Caller no longer running, last stopped +7s160ms because: timed out while starting
       at android.os.Parcel.createException(Parcel.java:1966)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
       at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
       at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
````

This is a known issue: https://issuetracker.google.com/issues/63622293. 

We have noticed that the SDK is still using the deprecated JobIntentService from the support library instead of the one that comes in the AndroidX SDK. We highly recommend to either start to use the JobIntentService from the AndroidX SDK or replace the whole thing with WorkManager + Worker. There is also a workaround https://github.com/optimizely/android-sdk/issues/194 in case you want to release something quick.

We are afraid we will have to stop using your SDK until that migration has been done.

Many thanks!

**Comment by MarioBoehmer** [comment]
Same for me. It's blocking me currently as well :(

**Comment by shivudarur** [comment]
It's happening for me as well. I had to remove the sdk completely. Eagerly waiting to be fixed.

**Comment by durgeshqualaroo** [comment]
@Hannibalem @MarioBoehmer @shivudarur We sincerely sorry for the inconvenience. Please connect with us at mobile@qualaroo.com. We need a few information regrading the survey that we cannot request here. Rest assured a dedicated mobile team is maintaining the repository and promising to act fast on it. Thank you for your kind patience.

**Comment by durgeshqualaroo** [comment]
The issue has been resolved and verified. Thanks for all your feedback that really helped us.

**Comment by southerneer** [comment]
> Thanks for all your feedback that really helped us.

@durgeshqualaroo it would really help the rest of us to post the fix back to this issue ;) We're having the same issue.

**Comment by jennifer-dickinson** [comment]
@durgeshqualaroo what version was this issue fixed in? We are still seeing this bug as of version 2.0.0

**Comment by vmantyla** [comment]
Still encountering this with the 2.0.0 version of the SDK.
