### ISSUE TITLE
Android  5.0 and 6.0 Crash when I Compile with minifyEnabled true

### ISSUE THREAD

**Issue by AndresTapiero72** [qualaroo/AndroidSDK#18]
The App crashes when I compile with minifyEnabled true in Android versions 5.0 and 6.0, 7.0 and up are ok.

```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.foodstuffs.newworldDev, PID: 11473
    java.lang.IncompatibleClassChangeError: Couldn't find kotlin.l.bv
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
        at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
        at java.lang.Class.getDeclaredAnnotations(Class.java:743)
```

I tried adding to proguard:
`**-keep public class com.qualaroo.** { *; }**`
and
```
-keep public class com.qualaroo.internal.model.** {
    private *;
    <init>(...);
}

```
But this does not fix the problem 

The version of qualaroo SDK used is: com.qualaroo:qualaroo-sdk:1.9.0

**Comment by durgeshqualaroo** [comment]
The problem has been taken care of in app v2.0.0
