### ISSUE TITLE
NPE: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by dianakarenms** [qualaroo/AndroidSDK#21]
Hi
I'm getting this error while fetching a couple of surveys with `showSurvey()`. 
_Some background:_ The surveys were created back in March 2021 and are currently working on iOS. New surveys with same conditions are working.
Here's the stack trace. Could you check what's going on?

```
D/QularooSDK: Acquired 3 surveys
D/QularooSDK: No failed reports found
I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=fbe20268-8895-455a-a327-61766a8629f2, tags={ com.qualaroo.QualarooWorker } ]
D/QularooSDK: Displaying survey friend-saved-survey
V/FA: Activity paused, time: 802865291
V/FA: onActivityCreated
I/BranchSDK: onActivityCreated, activity = com.qualaroo.QualarooActivity@b795821
D/Breadcrumb: onCreate com.qualaroo.QualarooActivity
I/BranchSDK: onActivityStarted, activity = com.qualaroo.QualarooActivity@b795821
D/QularooSDK: Steps left: 8
V/FA: Activity resumed, time: 802865339
D/TrafficStats: tagSocket(280) with statsTag=0xffffffff, statsUid=-1
I/BranchSDK: onActivityResumed, activity = com.qualaroo.QualarooActivity@b795821
D/Breadcrumb: onResume com.qualaroo.QualarooActivity
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rover.android, PID: 16208
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at com.qualaroo.ui.g.a(Unknown Source:0)
        at com.qualaroo.ui.g.a(Unknown Source:131)
        at com.qualaroo.ui.i$a.a(Unknown Source:6)
        at com.qualaroo.ui.h$h$a.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by durgeshqualaroo** [comment]
@dianakarenms Thank you very much for reporting. May I know the Survey ID please that is not working?

**Comment by durgeshqualaroo** [comment]
@dianakarenms Eagerly waiting for the Survey ID for the further investigation.

**Comment by dianakarenms** [comment]
@durgeshqualaroo Is the Survey ID the one at the url?
If that's right, these are the IDs of the failing surveys `214423` and `214293`

**Comment by durgeshqualaroo** [comment]
Thank you. This is what I was requesting for. I am moving ahead now. Will
update further.

**Comment by durgeshqualaroo** [comment]
I am glad to confirm that the issue has been resolved and you will not experience this problem again.
