### ISSUE TITLE
Crash on initializing the Qualaroo SDK

### ISSUE THREAD

**Issue by sumit007** [qualaroo/AndroidSDK#4]
11-29 13:33:25.227 29792-29792/com.nestaway.customerapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.nestaway.customerapp, PID: 29792
                                                                          java.lang.RuntimeException: Unable to create application com.nestaway.customerapp.controller.AppController: com.qualaroo.internal.c
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
                                                                              at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                           Caused by: com.qualaroo.internal.c
                                                                              at com.qualaroo.internal.a.<init>(Unknown Source:26)
                                                                              at com.qualaroo.Qualaroo$Builder.setApiKey(Unknown Source:2)
                                                                              at com.nestaway.customerapp.controller.AppController.onCreate(AppController.java:94)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
                                                                              at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                              at android.os.Looper.loop(Looper.java:164) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by scana** [comment]
Hi @sumit007! Thank you for you report. Which SDK version are you using?

From the stack trace it seems like you are trying to provide an invalid API key.

After creating a survey of an *SDK* type, you can grab your API key from here:
<img width="1094" alt="step_1" src="https://user-images.githubusercontent.com/1139325/33369632-7b0d67ac-d4f5-11e7-825b-a49bfce342c0.png">

<img width="445" alt="step_2" src="https://user-images.githubusercontent.com/1139325/33369635-7c98768e-d4f5-11e7-984c-ea8362d62a75.png">

If you are using a correct API key and still encountering this error, please reach me via e-mail: marcin@qualaroo.com

**Comment by sumit007** [comment]
@scana thank you,  
I am using API version 1.4.1. It will be great if we have a detailed documentation for In-app Mobile survey. You are right I am using a wrong API key and this happened because we are unable to generate the survey for the Mobile App. Whatever Survey we create is always in Draft and there is no option for us to make it live and getting a error [(Image attached)](https://help.qualaroo.com/attachments/token/IMQq2A0yeyhtEBeFWSZ0pM1ak/?name=Screen+Shot+2017-11-29+at+4.10.42+PM.png).

<img width="1279" alt="screen shot 2017-11-29 at 4 10 42 pm" src="https://user-images.githubusercontent.com/10415492/33372106-dc326e2e-d522-11e7-92ef-a54bab2eb9c0.png">

**Comment by scana** [comment]
@sumit007 could you please contact us through either https://help.qualaroo.com/hc/en-us/requests/new or support@qualaroo.com so we can create a new app-site for you?

**Comment by sumit007** [comment]
@scana Request raised, Thank you.
