### ISSUE TITLE
App crash when calling showSurvey() in sdk 1.4.2

### ISSUE THREAD

**Issue by chapp-hk** [qualaroo/AndroidSDK#5]
12-08 12:02:36.177 23935-23935/hk.easyvan.app.client E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: my.package.id, PID: 23935
                                                                       android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                           at android.app.ContextImpl.startActivity(ContextImpl.java:738)
                                                                           at android.app.ContextImpl.startActivity(ContextImpl.java:725)
                                                                           at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
                                                                           at com.qualaroo.QualarooActivity.a(Unknown Source)
                                                                           at com.qualaroo.Qualaroo$1$1.run(Unknown Source)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

It still crash after clean and rebuild. And even reinstall the app also not help.
I initialize Qualaroo SDK in Application class with:
Qualaroo.initializeWith(this).setApiKey("key").init();

Android Studio version :  3.0.1
Build tool version : 27.0.2
compileSdkVersion : 25
targetSdkVersion : 25

**Comment by scana** [comment]
Thanks @chapp-hk.
This will be fixed in `1.4.3` - we will release it in about 2-3 hours.

**Comment by scana** [comment]
Hey @chapp-hk, this bug is now fixed. 
Please switch to version `1.4.3`.
